version: '3'

services:
  db:
    image: mongo
    container_name: koomtone-db
    environment:
      - MONGO_INITDB_DATABASE=koomtone
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
  
  server:
    build: .
    container_name: koomtone-server
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    restart: always
  